### ISSUE TITLE
pom.xml:11-13: Automate deployment with CD. Use `publish`...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/oot#5]
The puzzle `3-64d19a42` from #3 has to be resolved: 

https://github.com/g4s8/oot/blob/41ddf6b0deeea76390928f4edf1edfa8981338e2/pom.xml#L11-L13

The puzzle was created by @g4s8 on 08-Nov-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by g4s8** [comment]
@rultor deploy

**Comment by g4s8** [comment]
@rultor deploy

**Comment by g4s8** [comment]
@rultor deploy

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor deploy

**Comment by g4s8** [comment]
@rultor deploy

**Comment by g4s8** [comment]
@rultor deploy

**Comment by g4s8** [comment]
@rultor deploy

**Comment by g4s8** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor deploy

**Comment by g4s8** [comment]
@rultor deploy

**Comment by g4s8** [comment]
@rultor deploy

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.6`

**Comment by 0pdd** [comment]
The puzzle `3-64d19a42` has disappeared from the source code, that's why I closed this issue.
